<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Safety" Id="{e95ddaa8-e370-40ac-9dda-44ae81d8a2b4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Safety
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Safety">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>